/**
 * CSP Nonce Utilities
 * 
 * Provides utilities to get and use CSP nonce in Next.js App Router.
 * The nonce is generated by middleware and passed via headers.
 * 
 * @author Dr. Philipe Saraiva Cruz
 */

import { headers } from 'next/headers';

/**
 * Get CSP nonce from request headers (Server Components only)
 * 
 * Usage in Server Components:
 * ```tsx
 * import { getNonce } from '@/lib/csp-nonce';
 * 
 * export default function Page() {
 *   const nonce = getNonce();
 *   return <script nonce={nonce}>...</script>
 * }
 * ```
 * 
 * @returns CSP nonce string or undefined if not available
 */
export function getNonce(): string | undefined {
  try {
    const headersList = headers();
    return headersList.get('x-csp-nonce') || undefined;
  } catch (error) {
    // headers() can only be called in Server Components
    console.warn('[CSP] getNonce() called outside Server Component context');
    return undefined;
  }
}

/**
 * Get nonce props for script tag with proper CSP nonce attribute
 * 
 * Usage:
 * ```tsx
 * import { getNonceScriptProps } from '@/lib/csp-nonce';
 * 
 * export default function Page() {
 *   const scriptProps = getNonceScriptProps('console.log("test");');
 *   return <script {...scriptProps} />;
 * }
 * ```
 */
export function getNonceScriptProps(code: string): { nonce?: string; dangerouslySetInnerHTML: { __html: string } } {
  const nonce = getNonce();
  
  return {
    nonce,
    dangerouslySetInnerHTML: { __html: code }
  };
}

/**
 * Get CSP nonce for use in inline styles (less common)
 * 
 * Usage:
 * ```tsx
 * import { getNonce } from '@/lib/csp-nonce';
 * 
 * export default function Page() {
 *   const nonce = getNonce();
 *   return <style nonce={nonce}>...</style>
 * }
 * ```
 */
export function getNonceForStyle(): string | undefined {
  return getNonce();
}

/**
 * Create script props with nonce for dynamic script injection
 * 
 * Usage:
 * ```tsx
 * import { getScriptProps } from '@/lib/csp-nonce';
 * 
 * const props = getScriptProps();
 * return <script {...props}>console.log('test');</script>
 * ```
 */
export function getScriptProps(): { nonce?: string } {
  const nonce = getNonce();
  return nonce ? { nonce } : {};
}
