# CodeRabbit AI Configuration
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

# Language and localization
language: pt-BR
tone_instructions: "Be professional, constructive, and focus on actionable improvements. Consider this is a healthcare e-commerce application requiring high security and compliance standards."

# Review behavior
reviews:
  # Request changes workflow behavior
  request_changes_workflow: false

  # High-level summary of changes
  high_level_summary: true
  high_level_summary_placeholder: "**CodeRabbit AI Summary**"

  # Poem feature (disable for professional context)
  poem: false

  # Review status
  review_status: true

  # Collapse walkthrough details
  collapse_walkthrough: false

  # Auto-review
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
      - "DRAFT"

# Chat feature
chat:
  auto_reply: true

# Path-based instructions for specialized reviews
path_instructions:
  - path: "src/app/api/**"
    instructions: |
      Focus on:
      - API security (authentication, authorization, input validation)
      - Error handling and proper HTTP status codes
      - Rate limiting considerations
      - LGPD compliance for data handling
      - Healthcare data protection (PHI/PII)
      - Asaas payment integration security
      - SendPulse WhatsApp integration best practices

  - path: "src/components/**"
    instructions: |
      Focus on:
      - React best practices and hooks usage
      - Accessibility (WCAG 2.1 AA compliance)
      - Performance optimization
      - Proper TypeScript typing
      - Component reusability
      - Responsive design considerations

  - path: "**/*.test.{ts,tsx,js,jsx}"
    instructions: |
      Focus on:
      - Test coverage and edge cases
      - Test isolation and independence
      - Clear test descriptions
      - Proper mocking and fixtures
      - Accessibility testing where applicable

  - path: ".github/workflows/**"
    instructions: |
      Focus on:
      - Workflow security and secrets management
      - Performance optimization
      - Proper error handling and retries
      - Cache usage and efficiency
      - GitHub Actions best practices

  - path: "src/lib/**"
    instructions: |
      Focus on:
      - Code reusability and modularity
      - Proper error handling
      - Type safety
      - Performance considerations
      - Documentation quality

  - path: "prisma/**"
    instructions: |
      Focus on:
      - Database schema best practices
      - Migration safety and rollback capability
      - Index optimization
      - Data integrity constraints
      - LGPD compliance (data retention, deletion)

  # Knowledge base for domain-specific context
  knowledge_base:
    code_guidelines:
      enabled: true
      filePatterns:
        - "docs/CODERABBIT_KNOWLEDGE_BASE.md"

# Enable specific review features
enable:
  - security_review
  - performance_review
  - best_practices
  - documentation_review
  - accessibility_review
  - test_coverage_review

# Abort reviews for certain patterns
abort_on_close: true
abort_on_update: true

# Custom labels to apply
labels_to_add:
  - ai-reviewed

# Files to ignore
path_filters:
  exclude:
    - "node_modules/**"
    - ".next/**"
    - "coverage/**"
    - "dist/**"
    - "build/**"
    - "*.lock"
    - "*.log"
    - ".git/**"
    - ".venv/**"
    - "__pycache__/**"
    - "*.min.js"
    - "*.min.css"

# Review scope
review:
  # Only review changed files
  changes_only: true

  # Exclude certain file types
  exclude_patterns:
    - "*.md"
    - "*.txt"
    - "*.json"
    - "LICENSE"
    - ".gitignore"
    - ".env.example"
    - ".env.local.example"

# AI model configuration
ai:
  # Use GPT-4o for complex analysis
  model: gpt-4o

  # Use GPT-4o-mini for simple changes
  light_model: gpt-4o-mini

  # Temperature for consistency
  temperature: 0.3

  # Maximum tokens for responses
  max_tokens: 2000

# Integration behavior
integrations:
  # GitHub-specific settings
  github:
    # Post summary comment
    summary_comment: true

    # Post inline comments
    inline_comments: true

    # Maximum inline comments per PR
    max_inline_comments: 25

    # Auto-approve non-risky changes
    auto_approve:
      enabled: false  # Keep manual approval for healthcare app

    # Request changes for critical issues
    request_changes_on_critical: true

# Custom prompts for specific scenarios
prompts:
  security_check: |
    Analyze this code for security vulnerabilities with special attention to:
    - SQL injection risks (even with Prisma)
    - XSS vulnerabilities
    - Authentication/authorization bypass
    - Sensitive data exposure
    - LGPD compliance issues
    - Healthcare data protection

  performance_check: |
    Analyze this code for performance issues:
    - Unnecessary re-renders
    - N+1 query problems
    - Large bundle size increases
    - Inefficient algorithms
    - Memory leaks
    - React Server Components optimization opportunities

  accessibility_check: |
    Analyze this code for accessibility issues:
    - WCAG 2.1 AA compliance
    - Keyboard navigation
    - Screen reader compatibility
    - Color contrast
    - ARIA attributes usage
    - Semantic HTML

# Notification preferences
notifications:
  # Notify on completion
  on_completion: true

  # Notify on critical issues
  on_critical_issues: true

# Rate limiting
rate_limiting:
  # Maximum reviews per hour
  max_reviews_per_hour: 10

  # Cooldown between reviews
  cooldown_seconds: 60
