name: CI - Test Automation

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

env:
  NODE_VERSION: '20'

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: TypeScript type check
        run: npx tsc --noEmit

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test -- --coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          fail_ci_if_error: false

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Install Playwright system dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps chromium

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_APP_URL: http://localhost:5000
          NEXT_PUBLIC_WHATSAPP_NUMBER: ${{ secrets.NEXT_PUBLIC_WHATSAPP_NUMBER }}

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          NEXT_PUBLIC_APP_URL: http://localhost:5000
          CI: true

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build
        env:
          NEXT_PUBLIC_APP_URL: https://svlentes.shop
          NEXT_PUBLIC_WHATSAPP_NUMBER: ${{ secrets.NEXT_PUBLIC_WHATSAPP_NUMBER }}

      - name: Check build output
        run: |
          if [ ! -d ".next" ]; then
            echo "Build failed - .next directory not found"
            exit 1
          fi
          echo "Build successful - .next directory created"

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Dependency vulnerability check
        run: |
          npm audit --json > audit-report.json || true
          cat audit-report.json

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-audit
          path: audit-report.json
          retention-days: 30

  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, e2e-tests, build, security-scan]
    if: always() && github.event_name == 'pull_request'
    steps:
      - name: Generate CI summary comment
        uses: actions/github-script@v7
        with:
          script: |
            const results = {
              lint: '${{ needs.lint.result }}',
              unit_tests: '${{ needs.unit-tests.result }}',
              e2e_tests: '${{ needs.e2e-tests.result }}',
              build: '${{ needs.build.result }}',
              security: '${{ needs.security-scan.result }}'
            };

            const getIcon = (status) => {
              if (status === 'success') return '✅';
              if (status === 'failure') return '❌';
              if (status === 'cancelled') return '🚫';
              return '⚠️';
            };

            const allSuccess = Object.values(results).every(r => r === 'success');
            const overallIcon = allSuccess ? '✅' : '❌';

            const summary = `## ${overallIcon} CI Pipeline Results

            | Check | Status |
            |-------|--------|
            | Lint & Type Check | ${getIcon(results.lint)} ${results.lint} |
            | Unit Tests | ${getIcon(results.unit_tests)} ${results.unit_tests} |
            | E2E Tests | ${getIcon(results.e2e_tests)} ${results.e2e_tests} |
            | Build | ${getIcon(results.build)} ${results.build} |
            | Security Scan | ${getIcon(results.security)} ${results.security} |

            ${allSuccess ? '**All checks passed!** ✅ Ready for review.' : '**Some checks failed.** ❌ Please fix the issues before merging.'}

            ---
            🤖 **Next Step**: CodeRabbit AI will review this PR automatically.
            `;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
